---
name: 
surname: Seamus McKinsey
# position: "      "
address: "  a"
# phone: +1 508 272 3248
www: seamus.netlify.app
email: "seamus.mckinsey@gmail.com"
github: seamus-mckinsey
linkedin: seamus-mckinsey
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
docname: resume
headcolor: 000000
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)

exp <- read_csv("data/experience.csv")

exp

```

# Skills
**Programming**: Expert in R, SQL, Hive HQL, Shiny; proficient in git, Linux/Unix shell (zsh/bash), Python, HDFS/Hadoop

**Methods**: Practiced in A/B testing, data visualization, ETL, statistical inference, econometrics, machine learning 

# Experience

```{r}
exp %>% 
  detailed_entries(role, dates, company, loc, details)
```


# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "BA, Economics; BA, English", "2008-12", "Williams College", "Williamstown, MA"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Presentations
```{r}
tribble(
  ~ What, ~ Year, ~ Institution, ~ Where,
  "Quality Measurement Model - Modeling Costs & Benefits of Health Care Quality Measurement", "2015", "INFORMS 2015", "Nashville, TN"
) %>% 
  detailed_entries(What, Year, Institution, Where)
```

